recommendation-engine:
    build: ./recommendation-engine
    container_name: trd-reco-engine
    ports:
      - "8002:8000"  
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - redis
      - rabbitmq
    networks:
      - trd-network